### ISSUE TITLE
Eclipse oxygen 导入maven项目失败

### ISSUE THREAD

**Issue by songofhawk** [Wizzercn/NutzWk#107]
导入时提示"Invalid project description.", 就没有然后了

**Comment by Wizzercn** [comment]
https://github.com/Wizzercn/NutzWk/blob/nutzboot-dubbo/wk-wiki/01.QuickStart/01.01.Environment.md

**Comment by songofhawk** [comment]
哦...收到, 谢谢. 但我open还是失败了, 只能IDEA打开是么?
