### ISSUE TITLE
Result.success().addData(getTree(menuMap, "")); 方法不支持oracle数据库

### ISSUE THREAD

**Issue by liumaobudao** [Wizzercn/NutzWk#113]
getTree(menuMap, "")      方法不支持oracle数据库，
建议menuMap.containsKey("")?getTree(menuMap, ""):getTree(menuMap, null)

**Comment by Wizzercn** [comment]
如果保证入库的数据，根节点parentId值始终是“” 是不是就不存在问题了？

**Comment by liumaobudao** [comment]
nbnb
