### ISSUE TITLE
2.0 idea tomcat 运行无法访问

### ISSUE THREAD

**Issue by zzvv** [Wizzercn/NutzWk#12]
rt.我貌似之前问过这个问题.囧~ 好像后面你修改了下配置,然后就可以tomcat默认启动,127.0.0.1:8080/访问项目了..忘记了

**Comment by Wizzercn** [comment]
nutz.cn 贴log

**Comment by zzvv** [comment]
fix .我删除本地文件,重新clone 能正常运行了..谢谢!
