### ISSUE TITLE
请问下这个框架式如何防止sql注入的

### ISSUE THREAD

**Issue by wuzhou126** [Wizzercn/NutzWk#13]

**Comment by wendal** [comment]
这得自己仿吧, 要不就是Druid连接池里面配置防火墙

**Comment by Wizzercn** [comment]
https://github.com/Wizzercn/NutzWk/blob/NutzWk2.0/src/main/java/cn/wizzer/modules/MainSetup.java

第321、333行，有两种自定义SQL写法的对比，其他用pojo类就行了。

**Comment by Wizzercn** [comment]
3.0使用动作链拦截非法请求
