### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by aifans** [Wizzercn/NutzWk#14]
错误现象：登录时提示系统错误，f5刷新即进入登陆后首页。
原因分析：分析代码，判断userservice的update出现异常。
尝试解决：user表的logingcount字段如果为null，则出现问题；手工置0，则正常登录。
解决方案：初始化时增加user.setLoginCount(0);。

**Comment by Wizzercn** [comment]
int类型默认值为0，update时不能忽略空字段，所以使用Integer类型。
已fixed，多谢。
