### ISSUE TITLE
百度编辑器无法全屏编辑的问题

### ISSUE THREAD

**Issue by Wizzercn** [Wizzercn/NutzWk#23]

**Comment by Wizzercn** [comment]
百度编辑器和模态框不兼容的问题：
https://github.com/fex-team/ueditor/issues/1173

通过教程修改后依旧不能解决，暂时可在微信模块编辑器配置文件ueditor.configWx.js里把全屏按钮屏蔽。。

**Comment by mengkeys** [comment]
我这边已经解决了 https://github.com/fex-team/ueditor/issues/1173
