### ISSUE TITLE
界面很漂亮,可是用来有些地方体验不好

### ISSUE THREAD

**Issue by liunewshine** [Wizzercn/NutzWk#3]
侧边栏总是跟着页面刷新,还会左右晃动,页面太窄没法自动利用整个屏幕,总体体验2.0不如1.0版本

**Comment by Wizzercn** [comment]
左右晃动已经解决了，有设置布局选项，另外因为是bootstrap皮肤没有使用iframe

**Comment by Wizzercn** [comment]
开发进行时，还未完成……
