### ISSUE TITLE
Tomcat下收到中文消息乱码,日志打印也是乱码

### ISSUE THREAD

**Issue by dllen** [Wizzercn/NutzWk#34]
2016-08-30 10:21:12,373 org.nutz.dao.impl.sql.run.NutDaoExecutor.printSQL(NutDaoExecutor.java:339) DEBUG - UPDATE wx_reply_txt SET title=?,content=?  WHERE id=?
    |  1 |                 2 |                                3 |
    |----|-------------------|----------------------------------|
    | ?? | ????????????????? | 124b70b6af424f0eb60da288e05a44cc |
  For example:> "UPDATE wx_reply_txt SET title='??',content='?????????????????'  WHERE id='124b70b6af424f0eb60da288e05a44cc'"

**Comment by Wizzercn** [comment]
URIEncoding="UTF-8"

**Comment by dllen** [comment]
This project must run in UTF-8, pls add -Dfile.encoding=UTF-8 to JAVA_OPTS

**Comment by Wizzercn** [comment]
@dllen 其实那个只是提示 并不是造成入库乱码的原因
