### ISSUE TITLE
坐等4.0 版本

### ISSUE THREAD

**Issue by TonyYule** [Wizzercn/NutzWk#41]
坐等4.0 版本 可以举个例子 结合APP 接口开发的案例么

**Comment by x55admin** [comment]
希望能给个app结合的例子，最好支出多部门权限，看好这个框架！

**Comment by TonyYule** [comment]
还有 app权限控制 保存token

**Comment by Wizzercn** [comment]
@x55admin @TonyYule 很好扩展啊，加张APP--APP 权限表即可。

**Comment by TonyYule** [comment]
@Wizzercn 如果是不想让APP用户能登陆后台呢 是不是得重新写Realm

**Comment by Wizzercn** [comment]
@TonyYule 这不简单，会员表扩展个字段，Realm加上这个查询条件不就行了。
