### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by louisliaoxh1989** [Wizzercn/NutzWk#46]
javax.servlet.ServletException: java.lang.NullPointerException
	org.apache.shiro.web.servlet.AdviceFilter.cleanup(AdviceFilter.java:196)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:148)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)

**Comment by louisliaoxh1989** [comment]
访问http://127.0.0.1:8080/nutzwk时报上面的错

**Comment by Wizzercn** [comment]
日志贴全一些，你这看不出问题。

**Comment by louisliaoxh1989** [comment]
嗯，看了下日志，是属于数据库造成的。我用的是10.1.17-MariaDB,在初始化表时报
Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at l

**Comment by wendal** [comment]
改一下BINLOG_FORMAT 就可以了
