### ISSUE TITLE
无法登录访问问题

### ISSUE THREAD

**Issue by su-coder** [Wizzercn/NutzWk#47]
部署到tomcat启动后，访问部署的应用时显示以下信息：

页面找不到

对不起，您访问的页面不存在。

单独war部署还是ROOT下都是这个样子。

**Comment by su-coder** [comment]
使用的分支为：  bootstrap-3.3.x

**Comment by Wizzercn** [comment]
http://127.0.0.1/sysadmin
http://127.0.0.1/platform/login

private 全改成 platform

**Comment by su-coder** [comment]
@Wizzercn 在哪里改？ 下载下来没改动就是这样子。
从源码工程中哪个地方改？

**Comment by su-coder** [comment]
bootstrap-3.3.x 与bootstrap分支功能上有啥区别啊？

各分支有说明吗？

**Comment by Wizzercn** [comment]
https://github.com/Wizzercn/NutzWk/releases
预览版，都有说明。
