### ISSUE TITLE
日志管理BUG

### ISSUE THREAD

**Issue by TonyYule** [Wizzercn/NutzWk#49]
角色分配菜单权限多个，查看日志信息不会换行

**Comment by Wizzercn** [comment]
不明白什么意思...

**Comment by Wizzercn** [comment]
v3.3.0以上   /controllers/platform/sys/SysRoleController.java 167行,删掉ID记录
v3.2.7以下  /back/sys/controllers/RoleController.java 167行,删掉ID记录

分配菜单ID过长导致日志列表页被撑的现象,非bug.
