### ISSUE TITLE
请问微信接口配置地址失败，怎么弄呢？

### ISSUE THREAD

**Issue by lbj2049** [Wizzercn/NutzWk#51]

**Comment by Wizzercn** [comment]
1、系统--系统管理--系统参数
配置项 AppDomain 改为域名

2、微信--微信配置--帐号配置
添加完成后，点修改，参考演示地址：
https://nutzwk.wizzer.cn/private/wx/conf/account/edit/f9c3d44415ad4d3293dd7f61a7fb53c1

**Comment by zzcv** [comment]
Hi!
请教下，我在IDEA中通过tomcat启动，
为了方便微信调试，通过ngrok 映射至本地tomcat8080端口，通过域名也能正常访问到本地应用系统；
完成微信--微信配置--帐号配置；
在微信公众号平台配置URL
> http://wx.xxx.com/open/weixin/api/4eafe300600547f69837f2e46320e9c0
[4eafe300600547f69837f2e46320e9c0为`Wx_config`表对应的id]；

提交保存提示**Token验证失败**;

不知是否因为在系统中添加完成后，点修改，显示的URL

> http://127.0.0.1/open/weixin/api/4eafe300600547f69837f2e46320e9c0 

对比演示地址显示的

> http://nutzwk.wizzer.cn/open/weixin/api/f9c3d44415ad4d3293dd7f61a7fb53c1

即必须要域名方式才能通过验证吗?

抱歉，重新打开了这个issuse.
