### ISSUE TITLE
最新的生成代码插件有问题

### ISSUE THREAD

**Issue by TonyYule** [Wizzercn/NutzWk#52]
layout("/layouts/platform.html"){

**Comment by Wizzercn** [comment]
1.2 是面对 3.3.0版本的
1.1 是老版本的  你用老版本

**Comment by wendal** [comment]
能兼容一下吗?

**Comment by TonyYule** [comment]
我就是用1.2    3.3.0版本的

**Comment by Wizzercn** [comment]
@TonyYule 3.3.0就是platform啊 
@wendal 这个得请 @enilu 帮忙了..

**Comment by Wizzercn** [comment]
https://plugins.jetbrains.com/plugin/8506?pr=idea
IDEA插件版本1.4，nutzwk-code-generator版本1.1

**Comment by enilu** [comment]
我先看看，好像通过模版文件就可以调整
