### ISSUE TITLE
fullcalendar控件无head

### ISSUE THREAD

**Issue by aifans** [Wizzercn/NutzWk#54]
在框架中尝试了一下自带的fullcalendar，发现日历的标题、头部按钮都不显示。
目前尚不清楚什么原因。
麻烦有空的时候帮忙看看。
谢谢。

**Comment by Wizzercn** [comment]
框架里是/assets/plugins/datepicker/bootstrap-datetimepicker 
demo地址：https://nutzwk.wizzer.cn/private/robot/order

fullcalendar我没用过...
