### ISSUE TITLE
nutzwk是否可以做成多模块的

### ISSUE THREAD

**Issue by sunhai1988** [Wizzercn/NutzWk#58]
nutzwk 中有cms管理功能，但是没有前台站点，如果想独立部署一个站点，用nutzwk做后台管理。
那么，前台用户访问web站点就做到一个系统里面了，更新维护都不方便。如果分开通过http调数据的话，如果后台挂掉，也影响用户访问。

如果能做到把cms  wzflow，shop  独立出来，在打包的时候集成进去。如果是3个独立项目的话 ，代码复用性又不高，如，我要弄cms的时候，是不是要拷贝一份到前台提系统。不知道我的理解对不对。

**Comment by WenTao-Love** [comment]
nutzwk vue不是就是前后分离了吗？
个人觉得要是像maven那种多模块的话，太难维护。有点交往过度了。

**Comment by sunhai1988** [comment]
也就是前台后台交互走http接口  是吧

**Comment by Wizzercn** [comment]
想法挺好，现在先实现功能，后面可以拆分。
现在拆分也很容易，熟悉了项目目录结构，类、views在什么地方，直接剪切粘贴即可。
（欠了一屁股技术债，好多东西要写..）

**Comment by Wizzercn** [comment]
@sunhai1988 哈，v3.3.3支持插件热插拔，理论上来说所有新功能都可以做成插件安装&卸载。

**Comment by Wizzercn** [comment]
done
