### ISSUE TITLE
用在生产系统如何？

### ISSUE THREAD

**Issue by zzvv** [Wizzercn/NutzWk#6]
1.有实际运用在生产系统中吗？
2.拆分开来单独使用，对项目其他框架的入侵性如何？例如，我只用到Dao，然后MVC这块依然采用Spring，能很好的集成吗？

**Comment by Wizzercn** [comment]
1.你说呢？
2.那还能提现nutz的优势么？

**Comment by zzvv** [comment]
nutz 是好玩倒是真，~ 就怕上生产。。
准备在项目组内部小范围推下，上nutz 省事好多。
在提issue中途，我已经开始添加进1.53了。
就是稍微前期有点学习成本，估计熟能生巧应该很快。

**Comment by Wizzercn** [comment]
安徽交通厅、安徽财政厅、合肥体育局、中国新媒体指数、游戏后台等等都用，有什么怕的，怕就别用。

**Comment by zzvv** [comment]
呵呵。

**Comment by wendal** [comment]
广告机平台，微信平台，内网oa，task系统，android/x86播放客户端

路过

**Comment by Rekoe** [comment]
游戏后端 充值系统 登陆服务器
路过
