### ISSUE TITLE
vue 版本 - nutzwk 4.0 开发任务

### ISSUE THREAD

**Issue by Wizzercn** [Wizzercn/NutzWk#62]
1、vue分支，从1.0升级为2.0；

2、封装模态框、datatables、表单验证等vue常用组件；

3、完成系统管理、CMS、微信等模块的vue实现；

**Comment by jww0924** [comment]
推荐看下饿了么开源的Vue2.0 UI库[element](https://github.com/ElemeFE/element)，常用组件都有封装，质量还是很高的

**Comment by Wizzercn** [comment]
@jww0924 点赞，多谢啦~~
