### ISSUE TITLE
nutzwk 数据权限如何处理

### ISSUE THREAD

**Issue by sunhai1988** [Wizzercn/NutzWk#68]
我们的数据列表是这样的，比如各分部进单的数据不能互相查看，总部可以看全部的数据。

怎么在一个列表里面处理呢？是在单子上加一个部门id 然后查询的时候 加上 in(部门id1,部门id2)  

有没有数据过滤的权限呢

**Comment by Wizzercn** [comment]
存一个单位ID、单位树PATH（也是唯一的），like '0001%' ；
或者考虑设计另外一套基于单位部门的可相互授权的表，然后取可查询的部门集合带到条件里；

**Comment by Wizzercn** [comment]
用PATH要考虑到删单位后值被重用的问题。
