### ISSUE TITLE
NutzWk列表点击某分页中条目编辑，返回时候怎么能返回本页而不是返回第一页

### ISSUE THREAD

**Issue by x55admin** [Wizzercn/NutzWk#70]
处理办法：index.html的
function initDatatable() {
        datatable = $('.datatable').DataTable({})` 中增加如下属性
"bStateSave": true,//是否打开客户端状态记录功能。

然后columnDefs属性中的edit链接"data-pjax"
" data-target="_blank"

**Comment by sunhai1988** [comment]
不错！！
