### ISSUE TITLE
关于微信公众号URL配置

### ISSUE THREAD

**Issue by zzcv** [Wizzercn/NutzWk#73]
抱歉，不知道怎么重新打开Issus。
#51 
Hi!
请教下，我在IDEA中通过tomcat启动，
为了方便微信调试，通过ngrok 映射至本地tomcat8080端口，通过域名也能正常访问到本地应用系统；
完成微信--微信配置--帐号配置；
在微信公众号平台配置URL
> http://wx.xxx.com/open/weixin/api/4eafe300600547f69837f2e46320e9c0
[4eafe300600547f69837f2e46320e9c0为`Wx_config`表对应的id]；

提交保存提示**Token验证失败**;

不知是否因为在系统中添加完成后，点修改，显示的URL

> http://127.0.0.1/open/weixin/api/4eafe300600547f69837f2e46320e9c0 

对比演示地址显示的

> http://nutzwk.wizzer.cn/open/weixin/api/f9c3d44415ad4d3293dd7f61a7fb53c1

即必须要域名方式才能通过验证吗?

**Comment by Wizzercn** [comment]
1、首先是公网的IP或域名地址；
2、必须80或443端口；
3、系统-系统参数-域名： 127.0.0.1 --> 改成你的公网域名或IP，无http:// 前缀,无 / 后缀；
4、确保你配的token等参数前后无空格。
