### ISSUE TITLE
依赖加载出问题

### ISSUE THREAD

**Issue by icnws** [Wizzercn/NutzWk#78]
最新的代码，nutz的依赖版本maven无法正常加载
个别类找不到对应对象，比如WxPayUnifiedOrder

**Comment by Wizzercn** [comment]
如果是IDEA，在pom.xml右击-->maven-->Reimport

**Comment by icnws** [comment]
`<nutz-version>1.r.61-SNAPSHOT</nutz-version>`
是这个版本过高的原因

**Comment by icnws** [comment]
改成1.60就可以了

**Comment by Wizzercn** [comment]
不要降低版本，照我说的做即可。
