### ISSUE TITLE
数据库脚本未通过oracle测试

### ISSUE THREAD

**Issue by aifans** [Wizzercn/NutzWk#81]
使用oracle时sql脚本执行错误。

**Comment by Wizzercn** [comment]
应该是quartz的sql引起的，之前oracle执行没问题，等会pc上测下

**Comment by aifans** [comment]
恩恩。刚刚比较了一下。确实是quartz的sql引起的。

**Comment by aifans** [comment]
BIGINT之类的数据类型不兼容造成的
