### ISSUE TITLE
wk-code-generator 使用了落后版本的Nutz

### ISSUE THREAD

**Issue by yorkane** [Wizzercn/NutzWk#86]
请作者更新。原有wk-code-generator有一些错误，我尝试修复，并使用项目内依赖。
结果wk-code-generator与Nutz1.62冲突, 无法相容。请作者修复，并更新项目集成方式，将Nutz-web依赖于wk-code-generator模块。

我会尝试做一个PR修复我所遇到的bug

1> 如果是自增主键，wk-code-generator无法有效识别
2>通过vm生成的视图模版只能用row.id，如果model中主键命名如果不是id，将会报错，datatable无法获取到主键名

**Comment by Wizzercn** [comment]
本框架约束主键名是id，并且是字符串类型。

**Comment by Wizzercn** [comment]
“wk-code-generator与Nutz1.62冲突,，无法相容”，这个没遇到过啊。可以把代码贴到 nutz.cn 。

**Comment by yorkane** [comment]
明白了，多谢回复。
也请将 wk-code-generator 从Nutz1.60的版本升级到1.62！ 两个版本差距不小。
具体报出的第一个错误记得是setOptBy方法出错，只换了wk-code-generator的依赖，明显框架差异导致的

**Comment by Wizzercn** [comment]
版本已升级，另外BaseModel 只有setOpBy 方法，没有setOptBy。nutz.cn 贴下日志。

**Comment by yorkane** [comment]
多谢，高效率的回复！赞！ 没在电脑边，确认好了上来贴日志
