### ISSUE TITLE
计划完成的工作

### ISSUE THREAD

**Issue by Wizzercn** [Wizzercn/NutzWk#9]
1、换掉velocity模板引擎，这个项目很久没更新了，ejs有木有java版本啊；
2、pjax全面支持，要重写很多页面、部分样式和部分代码；
3、分页换成datatables，这个前台JS有现成代码，后台代码要做修改；

PS：招募代码贡献着，可分享nodejs同类项目部分代码供参考，用于优化本框架~~

**Comment by wendal** [comment]
擦,你转行做nodejs了?

**Comment by Wizzercn** [comment]
哪里有转换,不还是程序员么..
