### ISSUE TITLE
求教，quartz的这些表 怎么用？

### ISSUE THREAD

**Issue by zaozaool** [Wizzercn/NutzWk#95]
sys_qrtz_blob_triggers
sys_qrtz_calendars
sys_qrtz_cron_triggers
sys_qrtz_fired_triggers
sys_qrtz_job_details
sys_qrtz_locks
sys_qrtz_paused_trigger_grps
sys_qrtz_scheduler_state
sys_qrtz_simple_triggers
sys_qrtz_simprop_triggers
sys_qrtz_triggers

**Comment by wendal** [comment]
就不应该会用到,这是quartz内部的事
